server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: order-shard2-service
  sql:
    init:
      mode: always  # Всегда инициализировать
      continue-on-error: true  # Продолжать при ошибках
      schema-locations: classpath:schema.sql

  shard:
    datasource:
      shard1:
        jdbc-url: jdbc:postgresql://localhost:5437/order_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          connection-test-query: SELECT 1
          pool-name: HikariPool-Shard1


      shard2:
        jdbc-url: jdbc:postgresql://localhost:5438/order_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          connection-test-query: SELECT 1
          pool-name: HikariPool-Shard2


  jpa:
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: create  # Используйте create для пересоздания таблицы
    # или
     ddl-auto: update  # Если хотите сохранить данные
#      ddl-auto: validate  # Проверяет, но не создает
    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
    show-sql: true

logging:
  level:
    ru.kuzya.orderservice.aspect: DEBUG
    ru.kuzya.orderservice.service: DEBUG
    ru.kuzya.orderservice.config: DEBUG
    org.springframework.jdbc.datasource.lookup: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
